### PR TITLE
Internet Explorer windows.scrollX/scrollY fix

### PR DESCRIPTION
**Pull request by rolandtoth**
replace window.scrollX with window.pageXOffset
replace window.scrollY with window.pageYOffset

### CODE REVIEW

**Comment by sunmockyang** [comment]
Looks good, but please indent using tabs and squash the commits together

**Comment by rolandtoth** [comment]
Thanks! I had some tough times with squashing commits together (I'm new to git), please check if it's OK now. Feel free to reject my PR and add these changes manually.

**Comment by sunmockyang** [comment]
Actually you can squash from within this PR. Thanks for contributing!

**Comment by rolandtoth** [comment]
Thanks! 

> Actually you can squash from within this PR

You mean here on GitHub?

**Comment by sunmockyang** [comment]
yep, I realized if you hit the merge button once, there'll be a triangle next to the second green button that shows up and it gives the option to squash and merge

**Comment by rolandtoth** [comment]
OK, thanks.

**Pull request merged**
